name: flutter_webapi_first_course
description: Projeto do primeiro curso de WebAPI da Formação Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  http_interceptor: ^2.0.0
  logger: ^2.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
